api:
  id: "19990327"
  listener:
    path: "/*"
http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    
papi-orders:
  host: "papi-orders.us-e2.cloudhub.io"
  protocol: "HTTP"
  port: "8081"
  basePath: "/api"